---
title: Resume
---

TIP: My links are in the footer

I’d like to pursue research/ internship opportunities during my undergrad in order to expand upon what I learn in my classes. I am attending University of Maryland, College Park in the Class of 2024, majoring in Computer Science, minoring in Math. I am in College Park Scholars at UMD. I’m driven, a team player, and love learning new languages and technologies. 

== IEEE Internship - Summer 2021

* Helped create a chatbot using dialogflow for internal use
* Many company wide integrations, including with google apis, help desk, pay days
* Worked in java and kotlin

== FRC Team 25, Raider Robotix - Lead Programmer, 2019 and 2020 seasons

* Github: https://github.com/RaiderRobotix/FRC-2020
* Wrote almost all robot functions, from remote control and pathfinding to interfacing with hardware
* Coded statistical software to track match data. Was used to select teammates during final rounds, helped us reach world championships

== Skills

* Rust, JVM Languages (Java, Kotlin, etc), Python, C++
* Linux Shells and Environments
* See my github account for my work, most notably my work for Robotics, Tech Club, and personal projects

== Education

* School: University of Maryland, College Park
* Major: Computer Science
* Minor: Math

== Other Experience

* Princeton Algorithmic Thinking - Summer 2020
   * Rigorous Summer program taught by Professor Rajiv Gandhi of Rutgers University, Equivalent to an introductory Comp Sci course, covers combinatorics, probability, number theory.
* Tech Club - Developed a https://github.com/nbttech/late-bus-signup[web app/site] that allows students to sign up for the late bus.

== Academics

* Taken Statistics classes in python and r that used data science libraries
   * Both in college, and through Columbia University’s http://www.columbia.edu/cu/shp/[Science Honors Program]
* https://scholars.umd.edu/programs/science-discovery-and-universe[Science Discovery and the Universe], College Park Scholars: Program focused on public understanding of science
