baseurl: "https://hybras.dev"
# baseurl: "https://www.terpconnect.umd.edu/~vchari/"
contentdir: content
layoutdir: layouts
publishdir: public
title: Hybras' Site
canonifyurls: true

DefaultContentLanguage: en
theme:
  - beautifulhugo
  - hugo-asciinema
metaDataFormat: yaml
pygmentsUseClasses: true
pygmentCodeFences: true
enableEmoji: true
# disqusShortname: XXX
# googleAnalytics: G-SL7P0NKJVB

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
  asciidocExt:
    extensions: ["asciidoctor-html5s"]

Params:
  subtitle: "Musings, Failures, Life"
  logo: profile.jpg
  favicon: favicon.ico
  dateFormat: "January 2, 2006"
  commit: false
  rss: true
  comments: true
  readingTime: true
  wordCount: true
  # gcse: '012345678901234567890:abcdefghijk'

Author:
  name: hybras
  email: vchari@terpmail.umd.edu
  gitlab: hybras
  github: hybras
  twitter: hybras1
  reddit: id9seeker
  linkedin: vc-
  stackoverflow: users/10725115/hybras
  # facebook: username
  # googleplus: +username
  # xing: username
  # snapchat: username
  # instagram: username
  # youtube: user/username
  # soundcloud: username
  # spotify: username
  # bandcamp: username
  # itchio: username
  # keybase: username

menu:
  main:
    - name: Blog
      url: "posts"
      weight: 1
    - name: About
      url: page/about/
      weight: 2
    - name: Resume
      url: page/resume/
      weight: 2
    - name: Tags
      url: tags
      weight: 3

security:
  enableInlineShortcodes: false
  exec:
    allow:
    - '^asciidoctor$'
