---
title: "Avatar: The Live Trashbin"
date: 2024-02-28T22:07:01-05:00
draft: true
---

I'm currently watching the Avatar the Last Airbender live action.
I think poorly of it. While I do think the show tarnishes the image of the original, thats only because the original is so good.

First things first, if this show came out independently today (if the original show didn't exist), I'd feel solidly meh. I don't want to be dramatic here, just trying to establish a frame of reference.
The pacing is poor and rushed, the dialogue excessive, and characters sometimes feel like a ghost is inhabiting them.

There are of course, reasonable explanations for all this.

== Pacing

The pacing is poor because they are cramming 20 half-hour episodes (that are really ~22 minutes due to ad breaks, credits, and title sequence) of content into 8 hour-long episodes.
They'd need at least a couple more episodes to bridge the gap.

Various storylines are cut and pasted into a grotesque anachronistic amalgamation.

This might sound pedantic, but every episode tries to take on far far too much, and fails to portray most of what it takes on.
I'm OK with massive reworking of characters and storylines, but instead things of being rushed to the point of non existence. This is another show wearing Avatar's skin.



=== Ep 5

In the 5th episode, Aang travels to the spirit world, inadvertently bringing Sokka and Katara along. Originally, Sokka is kidnapped by Hei Bei. This change is not a big deal (the idea that he (and Katara) are kidnapped remains).

It seems this is based on "The Winter Solstice" ... Except we see Hei Bei, Koh, Wan Shi Tong, a spirit fox, the Fog of Lost Souls, and the Mother of Faces all in the same episode.
Its a spirit world bonanza.
Except, Wan Shi Tong is not in this season, the fox is presumably an illusion to Tong's assistants,Koh is from the season finale, the Fog of Lost Souls is from Korra, and the Mother of Faces is from a comic.

Each spirit's appearance is short and contributes very little to the plot. Koh steals the spotlight from Hei Bei as episode's villain. In the process, we lose the show's original meaning (balance with nature is reduced to a throwaway scene of Aang planting an acorn).
This is out of character for Koh as well: Koh prefers to bait his victims, and then pounce.
Instead here, he kidnaps people and waits to "steal their souls" (which the show portrays as faces, even though we know from the Mother of Faces comic that Koh's face stealing does not alter personality).

The other spirits appearances are cheapened.
The fox and Wan Shi Tong deliver token lines.
The Fog is but a distraction while Koh takes his victims (in Korra, the Fog itself is punishment)


== Katara

== Iroh

== Aang

* maturity
* Kyoshi , Roku

== Gritty Tone

== Sokka

== CGI

* Opening Sequence
* Each bending discipline
** Fire bending: burning alive and remote ignition
* June's mole rat animal