---
title: Aang
---

== Adaptation

Roughly corresponds to the first 3 episodes of the original season.

== Exposition

There is terrible exposition. There is a flashback-ish to set the tone. I didn't like it. And gran-gran unceremoniously recites the original show's opening lines. I forgave these things.

More importantly, they immediately reveal Fire Lord Ozai. This would be fine on its own. The live action fire bending is impressive (burning people alive, igniting fires at a distance), and it plenty compensates for the lack of intimidation by showing his face.
Unfortunately, its a significant change.
In the original, We don't even see Ozai's face when he "duels" Zuko.

== Genocide

While we receive the theme of genocide, it comes too soon.
Aang is informed at the South Pole.
As a result, his grief at the Southern Air temple is not accompanied by shock.
The exposition also gives us Aang's backstory.
We already know about Gyatso and the pressure Aang was under from the Air Nomad elders.
Its too much, too quickly.
We're supposed to be horrified, but its just sparkling sadness.

== Agni Kai

The Agni Kai between Zuko and Zhao is deleted, replaced with an uneasy alliance to hunt Aang.
While the distrust / animosity between them is retained, we lose a chance to see Iroh's moderating influence on Zuko.

== The Special Effects and their Plot Relevance

We see how Aang ends up in the south pole from the exposition.

He goes into the Avatar State and freezes himself and Appa.
The writers use this to rob us of the later Avatar State display, where Aang surprises us with water bending.

Similarly, we also lose the scene of Aang deflecting a firebolt from Zuko / Zuko's ship.
Katara deflects it instead.
Its supposed to be an impressive show of airbending,
that tells us that Aang is unique in multiple ways: he is an Airbender, he is an Airbending master, and he has the Avatar state.

We learn about Aang's airbending prowess from the exposition (his childhood at the Southern Air Temple).
