---
title: Warriors
---

== Adaptation

Roughly adapts "The Kyoshi Warriors".
At the time of writing, wikipedia alleges that it also contains material from "The Southern Air Temple".

== A minor but glaring pacing issue

The Kyoshi warriors capture the Gaang upon their arrival.

* The Gaang arrives
* They are ambushed
* Aang darts around but is surrounded
* Suki doubts Aang is the avatar
* _immediately_ the Kyoshi statue's eyes glow

The pacing is atrocious. Simply swapping steps 3, 4 could've fixed this.

== Suki's Mother

The island mayor is gender-swapped to be Suki's mom. I like this change. It impresses upon us the history of the Kyoshi warriors and the island.

She also tries to prevent Suki from becoming attached to Sokka, a good way to show Suki's independence and competence despite her youth.

== a mistake Sokka would make: Romance != Feminism

The romance between Suki and Sokka is bad. i got major r/menwritingwomen vibes here. The point of the episode is lost.

Suki sexually harasses Sokka by gazing upon him undressed without his consent (she sneaks up on him, peering into the bathroom, he tries to cover up).
If the genders were reversed, there would rightfully be uproar.
The implication is that the writer thinks its ok when the genders are reversed (the writer is acting out their fantasy here).
Not going to get into the feminist theory behind this.

Sokka's warrior education is replaced with a steamy private training scene.
The feminist message is almost completely gone.
If instead he joined a group session (like the original), and/or the sexual tension was more subdued, the writers COULD HAVE HAD BOTH FEMINISM AND SEXY SEX. BOTH!!

Sokka does not don the Kyoshi attire.
Its not critical to the feminist message (his humility sends a bigger message than face paint).
That made me sad.

Its very clear this episode was sterilized by idiotic men and corporate whitewashing.

== The Waterbending Scroll

Katara also receives a waterbending scroll from her grandmother upon departing home.
This means "The Waterbending Scroll" episode was deleted.

== Aang

In the original, Aang is goofing around and attracts the Fire Nation to Kyoshi island.
Instead, here he is studying what it means to be the Avatar.
Aang takes his duties seriously a lot earlier than the original (there he waits till Roku slaps some sense into him in "The Winter Solstice").
The Fire Nation finds Aang through their own surveillance.

Kyoshi possesses Aang and helps him defeat Zhao and his forces.
Kyoshi is very inappropriately harsh towards Aang, he is a child.
This scene is a replacement for Roku possessing Aang in "The Winter Solstice".
The message of the Avatar's power definitely gets across, though I didn't like the actual fighting/cgi too much.
I have no problem with Kyoshi possessing Aang instead of Roku, but I don't like that Roku shows up later.
They should pick one Avatar mentor for Aang and stick to it (honestly, wouldn't mind a female Roku).
I also think this should apply to the reworked title sequence in the previous episode (where they have Kyoshi instead of Roku).
