theme:
  - 'github.com/janraasch/hugo-bearblog'
  - 'github.com/hybras/hugo-asciinema'

module:
  imports:
    - path: 'github.com/janraasch/hugo-bearblog'
    - path: 'github.com/hybras/hugo-asciinema'
    - path: 'github.com/hybras/hybras-theme'
      disable: true