theme:
  - 'github.com/hybras/hybras-theme'
  - 'github.com/hybras/hugo-asciinema'

module:
  replacements: 'github.com/hybras/hybras-theme -> ../../hybras-theme '
  imports:
    - path: 'github.com/hybras/hybras-theme'
    - path: 'github.com/hybras/hugo-asciinema'
