---
title: Scholars Serves
date: 2020-11-10
tags: ["scholars"]
---

== The Issue

Poll workers skew towards the elderly, and the current pandemic makes its risky for those with compromised immune systems to interact with hundreds of strangers.
The underlying issue is that people ages 18-29 are not as politically active as older citizens.
We don't vote as much, we don't run for elected office as much, and we don't work as poll workers as much.
This means that our pandemic caused a shortage of poll workers.
The underlying issue is that voting is downright difficult in this country.
Ideally, all adults would be automatically / immediately eligible to vote.
In practice, voter registration is time consuming / confusing, political parties don't campaign as frequently to younger voters, and employed individuals may have difficulty taking time off to vote on a Tuesday.
There is enormous incentive for politicians (of both parties) to disenfranchise voters who disagree with their policies.
When voters are {not aware of , incapable of voting in their best interests}, politicians can enact policies that increase their power at the expense of the citizenry.
As such, https://represent.us/action/no-the-problem/[Congress is literally not a democracy].
And of course, echo chambers online have fueled misinformation, polarization, and obscured https://www.npr.org/2019/06/07/730183531/poll-majority-want-to-keep-abortion-legal-but-they-also-want-restrictions[broad agreement] on certain issues.

== Myself

Is was very difficult registering to become a poll workers.
I received spam emails from some activist site to fill out a form.
I then went to my county's site and found an updated form.
A couple of weeks after that I learnt that registration had now moved online.
Election Day was also strenuous, everyone seemed very uptight (though that was probably just me), and we were all under tight scrutiny from each other.

Being a poll worker isn't a career, but being an election official is.
I really wouldn't want to do this in the future.
Provisions for mail-in voting were massively expanded due to the pandemic, and I hope that our nation moves entirely to this method.
It allows votes to be counted early, people to vote at their leisure and in private, and additional information can be mailed with each ballot (NJ had several ballot propositions which came with background info).
Honestly I hope no one has to do this when better alternatives are readily available.

To other people considering service experiences, my message is that a little time/effort from you can translate into massive impact.
I volunteered one day of my time and in turn helped I don't know how many people participate in democracy.
As I stated in #5, the way I chose to help people wasn't the most efficient, but I still managed to meet so many new people.
All of them deserve to have their voices heard and I'm sure any of them would do the same for me in a heartbeat.

== Additional reflection

. I guess it was a bit of both.
I wanted to help other people, but I was also really curious to see how elections are run.
Part of it was also availability: I was reached out to so I didn't have to go searching for opportunities.
. NJ implemented universal mail in voting for the election (I also mailed in my ballot), so the people I helped had terrible mail service, didn't trust the mail, or couldn't reach a drop box.
That felt super weird, to be checking people in when I didn't even vote in-person myself.
. I felt proud of myself for participating afterwards, because the whole "operation" was run extremely efficiently.
There were / are allegations of election fraud, but knowing the number of people involved from both parties makes me scoff.
I also found out that people had blocked our highways a couple days earlier while I was working, which was extremely infuriating.
