---
title: "Green Bank Excursion"
date: 2021-10-16
description: I went on a school trip to the Green Bank observatory in West Virginia
tags: ["scholars"]
---

NOTE: https://photos.app.goo.gl/AJ4FRULhHeL6aPXm6[Our Photo Album]

I _loved_ this excursion. It was _magical 🪄_, and perfectly timed in the semester before work started ramping up too much. 

== Hiking, Spelunking

The hiking was so fun. We got awesome views of the neighboring mountains and town, lots of exercise, picnic food, and great conversation while hiking. 

I got to learn more about the freshmen that joined us on the trip. We talked about everything from how technology is transforming society to us politics to nuclear power ☢️. I can't believe we covered so much ground on hike of just a few hours. 

I felt a lot worse about the spelunking. I seemed more of a tourist trap to me. Our tour guide (though engaging) made up a lot of folk lore to describe the geological formations we saw, and got the science behind the formations wrong a few times. I didn't like that at all 🤬.

Spelunking seemed more of a sightseeing time killer to me, but I don't think anyone else felt close to the same way.

== Green Bank Observatory

I forgot the name of the employee who took us around, but they were very knowledgeable and professional. They took a complicated topic, operating a radio telescope and interpreting its data, and turned into something we could understand after a quick explanation. Also they gave us helpful packets. 

There were lot of jargon, but nothing I hadn't already heard from other astronomy discussions or from Peel. I learnt that we could figure out roughly how fast our galaxy was rotating by looking at whether certain stars were moving toward us or away from us. 

== Final Thoughts

Being without internet/wifi for a few days was eye opening. I had to download all my content beforehand, and it took time to figure out what I even needed to download. It was awesome for hanging out with my friends. Who knew, hours of isolation w/o internet is great for bonding. We played so many board games... I absolutely recommend this excursion to everyone, its worth making time for.  