---
title: Scholars Reflection
date: 2021-05-12 22:44:16 -0400
tags: ["scholars"]
---

== Branching out

This semester, I took "Are We Rome", a course on whether America is a descendant of the Roman empire.
I took the course because of my gen-ed requirements, but I was _really_ surprised.
Part of university is trying stuff outside your comfort zone, and this was my foray into that.
It turns out that people just _love_ to compare America to Rome for just about anything, or use Roman culture for advertising.
This makes it hard to draw a comparison.
_All_ of the comparisons I saw in class were political (from the left and right), making them hard to trust.
In the end, I decided that "Rome v.
America" was just a common myth, not worth even taking the energy to refute any argument.

While the material was interesting, I'm not sure if a _class_ 📚 was needed for me to figure this out.
Then again, it was only 1 credit and the workload was low.
This kind of in-depth about face is impossible in high school.
Very few of the courses you take are an elective, and high schoolers don't have majors.
We also touched a bit on the worth of studying the classics, of which sadly I'm unconvinced.

== Forming Relationships

The other big part of university is forming relationships and getting job experience (ps I got an internship, post incoming).
I really struggled to connect with my professors this semester.
Of the 2 courses I took towards my major this semester, one was small (Discrete math, ~20 kids) and the other was large (Programming Languages, ~230 kids).

My discrete prof was extremely knowledgeable, and we got more time with him (thanks to class size).
But the material wasn't so interesting, I found him boring, and the class's discussion was super early.
These are all _personal_ problems that _I_ need to work on.
There was a bit of resentment between the class and the professor, because the material was well beyond what the exams required (the course was honors).
Its a new kind of stress to have struggle with the material, enter the exam sweating bullets, and see the questions barely require having studied or attended lecture.

My other course felt like the opposite.
The material was so great.
The technology that programmers use on the job change so fast, and it was refreshing to actually talk about modern tools and areas of research.
While the class was huge, most kids didn't speak.
Prof Mamat was great, cracking jokes, giving mostly relatable examples, and not trying to bore us with endless slides.
I went to OH a few times and emailed him, and his PL research seems pretty interesting.
I would love to research under him, 🤞.

== Zooming out

I'm so done with zoom.
Teaching is hard, being engaging online is even harder.
I don't blame my teachers, but I'm ready to give out.
Its so hard to connect with professors in lecture, and forget about other students.
Groupme is such a terrible chat platform, its notifications keep being dropped, and it lacks features.
I know the names of about 5 fellow students per class, with the exception of SDU.
I can feel my motivation draining away.
Thankfully, UMD has mandated vaccination and our https://umd.edu/covid-19-dashboard[vaccination rate] is increasing smoothly (we're not exceptional, the US is currently vaccinating at breakneck speed).
I'm desperate to return to in-person.
I think I'd hug a stranger at this point.

I'm so nervous for fall.
Will I be able to make friends?
Does everyone already have friends and I'm a loner?
I think I need to be "rehabbed" into forming friendships.
What will it be like, meeting everyone as a _sophomore_?

== Conclusion

This semester was solidly 🆗.
I want to burst out of home and into university and _meet people_, but I'm worried it won't go well.
