---
title: IEEE Internship
date: 2021-05-17 10:34:55 -0400
description: I got an internship for 2021 summer
tags: ["job", "diary"]
---

____
My mom used to work at IEEE.
She didn't help me get this position, and no longer works there.
____

I got an internship at https://www.ieee.org/[IEEE] 🥳.

== Lead Up

I applied to ~40 summer positions.
This was across the 2020-2021 academic year.
I _should've_ applied to more places, and I applied to only of handful research positions or co-ops.
Stories of needing to apply to 100+ places are common, especially for people who are just starting out.
I was rejected or ghosted from everywhere except 2 places: IEEE and Code Ninjas.
These last 2 were both places that I applied to relatively late, in April.

=== https://www.codeninjas.com/[Code Ninjas]

They were looking for a summer instructor.
The big qualification was someone who was good with kids.
I think I'm _ok_, I think I'm patient, but not very peppy.

I got recommendations from {a parent of a code ninjas kid, schoolteacher who used to work at the franchise}.
These got my foot in the door and gave me a good chance.
My _interview_ went ok (I possessed all the technical skills, but like I said, that's not what was most important).

I was assumed to roam around, and eventually ended up helping some kids with their assignments.
I'm not sure if I was being observed, and this was secretly all a test.

In the end, I turned this offer down after I got the IEEE position.

=== https://en.wikipedia.org/wiki/Institute_of_Electrical_and_Electronics_Engineers[IEEE]

I applied to a generic IT position (ah, IT the bane of CS students).
I assumed I'd be maintaining existing projects.
My mom correctly guessed who the interviewers would be, one of them being her old boss 😟.
The boss joked that "there could only be 1 Chari" at IEEE.

I though the interviewers would be by HR, but instead it was under the people I would directly work under.
That was a pleasant surprise.
They asked me to list my experience and skills (so just regurgitate my resume).
I talked about my time at uni, high school robotics team, and high school coding club.

They were impressed by the breadth of my experience (thank you robotics 🙏).
By now I know several different languages, and have used version control, CI, hardware, etc.
(Am I re-regurgitating my resume?).
Nothing _crazy_, just apparently more than the average high schooler.

== The job

I'll be starting in June.
It'll be remote.
I hear IEEE's CEO (or at least, whoever controls the Piscataway office) is _itching_ to bring everyone back in.
Ironically, this is one of the reasons my mom left IEEE.

Unless I work on something interesting and generally applicable, I won't post about my actual duties at IEEE.
Trade secrets and all that.
