---
title: "Euphoria"
date: 2023-11-01T20:10:29-04:00
tags: ["diary"]
---

I finished the first season of Euphoria.
This was my 4th? attempt at watching it, and I'm glad I did.
The first few times I found the characters strange and stuckup.
This time I found them extremely relatable, with everyday problems and an utter lack of healthy coping skills.
A good year or two of therapy would set almost every character straight.

It makes me so sad that none of the characters (except for Jules) can see a long term future for themselves.

== Characters Synopsis

* Rue has "mental conditions" and hasn't processed the grief of losing her father. She turns to drugs to cope.
* Jules is treated poorly by everyone (every man). She's good enough to fuck, but not to date. She embraces casual sex to get thrills, the feel of being wanted, and a feeling of control over who she spends her time with. Unfortunately, she also is exposed to risky situations (Nate and Cal jacobs).
* Kat is treated poorly by everyone (every man) because of her body. She embraces casual sex and sex work to get thrills, the feel of being wanted, and a feeling of control over who she spends her time with (sound familiar). Unfortunately, she doesn't leave herself vulnerable enough for more emotionally fulfilling relationships (like with ethan).
* Maddy is poor and she knows it.  She desires to move up in life, and correctly identifies "finding a rich man" as one of the best ways to do it (hey, starting a business or career is hard). She plays the necessary part to get Nate Jacobs, and ignores his abuse because she has no healthy relationships to model.
* Cassie witnesses her beautiful parents be treated well due to their appearance. She is sexualized from a young age and so believes she needs her appearance to find love. Since no men have appreciated her for her personality, she can't (can't?) identify those who do.
* Nate Jacobs is toxic masc. He is aggressive, entitled (sexually and otherwise), unable to express his emotions or desires, and measures himself against a masculine ideal. He is unable to even think about his sexuality, instead choosing to fit the stereotype and pursue Maddy. He isn't vulnerable with anyone.
* McKay is similar to Nate, just a lot more disciplined.
