---
title: "Male Chowvinism"
date: "2023-10-01T15:24:04-04:00"
description: Some gender norms transcend cultures
tags: ["diary"]
---

[WARNING]
----
This occurred during the summer, but I'm only writing about it now. 

Also, I'm aware the title is misspelled.
----

My father has a classmate who married a czech woman.
I found this extremely interesting for many reasons:

* Its more common for 2nd generation immigrants to marry out then 1st gen. All of the mixed indian-white marriages I know are this way. Also its usually the woman marrying out, not the man.
* My father's background makes it seem like he'd be opposed to something like this, and most of his friends / our family seem the same. (I have an uncle who declared he'd honor kill a daughter of his who'd eloped.)
* Czechia??? All the indian immigrants I know went to the USA, UK, or Australia (all english speaking nations).

The classmate and his family (three little ones!) were coming for a nyc vacation and were going to stay with us. I was excited to see the adorable little faces. I forget their ages, but I think they were 12, 7, 1? The youngest was walking-crawling.

The mom's hung out, and the dad's hung out, and me and my brother kept the kids company. The middle child asked me if I was a girl ... She showed off her legal knowledge, telling us about some differences between the czech and american legal systems. I got the sense the mom might've given up her career for her children.

The husband was still working ¿a little? so the wife was officially on child duty. Of course we all doted on the kids, but the littlest one remained attached to her mom. The baby more or less did that baby thing where you explore a little then return to home base (mom) for the whole stay. Every so often baby would chew on her mom's legs (also adorable), she was probably teething. I'm sure it was exhausting for mom.

[quote]
____
Me: Plays lego video games and tennis with the older kids for a whole day
Their Mom: Wow you spent the whole day with them!
Me (_confused_): ¿¿You spend the whole everything with them??
My Mom: I'm so happy/proud you said that
____

Their flight was delayed by a day or 2 so the family spent a week with us instead of a couple days, which was fun.

The kids were picky about indian food.
My mom prepared a standard South Indian feast on the 1st or 2nd day, and the kids stuck to the more normal looking / blander items.
They jumped at the chance to eat ice cream afterwards.
They didn't eat Indian food for breakfast (I give them a pass on that since I don't either).
The mom said she was starting to learn Indian dishes, which I found impressive.
The kids said their father was not learning Czechian dishes.

On the last? night with us, it was clear the kids had not been eating enough so we went out for pizza
Their family ate meat, but we were veg.
Me and my brother didn't care (he secretly eat meat).
My mom was willing to accommodate for the kids.
My father is militant about being veg.
I think he _might_ not have cared if we ate in separate rooms, but I never got to test that idea.
*Their dad made them eat in the car.*
This is something I've noticed about Indian culture, where meat eaters will eat veg in the presence of vegetarians. I question if India's veg/nonveg coexistence is about freedom or about  religious cleanliness.
My brother and mother were out. Me, my dad, and their dad ate inside.
The kids and their mother ate in the car.
I was deeply uncomfortable the whole time.
I asked them them to come inside multiple times, but the mom refused (out of indignation I think).
Their father brushed off my concerns.
He didn't want the meat smell to permeate the house.
How kind of him.

Their mom bought a thank you card for us. She signed everyone but her husband's name.
