---
title: "Revenge"
date: 2023-05-25
subtitle: "An analysis of my desire for revenge"
description: "I had a fight with a couple of my friends, and I wanted revenge. I saw some parallel between my desire and why the USA's criminal justice system focuses on punishment (incarceration) over rehabilitation."
image: ""
tags: ['diary']
---

All my life, I've been misunderstood and disrespected. I suspect autism, but a diagnosis will have to wait (hooray American healthcare!).

This was part of a fight between me and a couple friends of mine. There was no resolution between me and my friends. Neither of us desired reconciliation. I've made minor progress about this. Sometimes I can accept/forgive my friends actions, my actions, and the pain we caused each other (_yes, this includes accepting/forgiving myself_). Other times I'm very angry and want revenge.

I think about reconciliation a lot (its moot now that I've graduated college). I miss my friends. Our mutual friends split time, with me receiving much less attention since I'm less assertive, more awkward, and only a single person (the other side involved 2.5 people). I also miss the friends I clashed with. I enjoyed their company, and I held one of my friend's opinion of me in high regard (_was it too high?_).

Reconciliation would involve a lot of effort from me. I would have to explain how I was hurt, to people who disregarded my feelings many times. Is this worth it? I would have to give them time and patience to understand, apologize, and change their behavior. This would do nothing to prevent similar misunderstandings from other people (_is this relevant?_), and might not prevent this from reoccurring between me and my clashing friends. It would also not heal the hurt I already felt.

Reconciliation would be so much easier if I were in a better position. If I were treated better by my friends (mutual and clashing), it would be easier to shrug this off, or I'd desire lesser revenge. I would have been _cumulatively?_ hurt less to begin with, _I think_. _Wait, does this even make sense? I was so hurt to begin with, why was I even friends with them?_

== Analogy

WARNING: I'm not a psychologist, sociologist, etc. What I say here may not be true. And my thoughts here are very shallow.

Say I was robbed of $50.

If I were rich, I could easily shrug this off. If I were poor, this would be a big loss (financially and emotionally).

If the government compensated me immediately (assume magical crime detection), and separately pursued the thief (either rehab or punishment), once again no big loss. I would be very willing to advocate for rehab of the thief / reconciliation between us since no money is at stake for me.

If the government only pursued the thief, then justice for me (my personal justice, not to society) would rely too much on the cooperation of the thief. I'm unlikely to get the money back, or an apology. If rehabilitation is pursued, there is a societal benefit (reduction in theft) independent of the personal benefit (apology, compensation). The thief could do either without doing the other. I don't have the same incentive to care about the social benefit over my personal one (psychology™️). If I can't get healing, then I went revenge. Incarceration, restricting freedoms, other punishments.

There's also the concern of not getting enough bang for your buck. Why was I so poor that stealing $50 was hurtful? I don't want the thief getting more help than I ever did, that feels like an incentive to do crime. And could have something been done to prevent the initial harm? If so, why wasn't it done?

CAUTION: I ended up regurgitating conservative talking points I thought I disagreed with: "not caring about social benefits", "incentivizing crime", "revenge". It seems the real difference between liberals and conservative on this issue is how wealthy you are. It is easy to support rehab when I didn't have skin in the game. This newfound sympathy for conservatives will probably last a day.

== Back to my Drama

Neither I nor my friends want to reconcile. I think they don't understand me, even though I've made a lot of effort to understand them. My understanding/compassion varies inversely with how angry I am, which is very variable. Sometimes I want to reconcile. Other times I want our mutual friends to take a stand against them and/or socially exclude them. My friends have been very clear about getting rid of me, excluding me from anything they organize, and preventing me from finding out about times our mutual friends are socializing. This is despite a promise to not do so.

My feelings about all this are too tied up with my own feeling of self-worth/insecurities. I'm sure its the same for my friends (wow, I'm pretty calm right now).

== Introspection

This is why everyone needs therapy. It took months to calm down and think through all this. Prolly would've taken 3 hours with a therapist.

I also partly see why priests enjoy special status now. They are assumed to show the kind of compassion/understanding in this post towards everyone. Hindering them would be an obvious form of self harm. I understood this about doctors/combat medics, but not priests. I get the phrase "Priests are held to a higher standard now". I assumed priests were useless, and therefore it was useless to expect more from them.


== Never Have I Ever (lost my shit)

NOTE: This section was written on Jun 12 after watching an episode from S3 of Never Have I Ever (the show is so much better than I remember).

The main character Devi is unstable and dramatic at times. Her (first brown) boyfriend's mother (Riyah) advises her son to end things, and the mama's boy (Nirdesh) complies, despite disagreeing. Devi retaliates by throwing coffee into her bf's face. Devi's mother, Nalini, temporarily excuses her daughter's behavior, defends her daughter, and insults Riyah.

There's a lot here.

Nirdesh seems really great (similar culture, hot, nice, smart), but at the end of the day he'll pick what's easy, not right. He's just a man. Just a brown man (derogatory).

Riyah was kind to Devi in person (helping Devi with a ¿panic attack?), but duplicitous behind closed doors (and failed to see her behavior as backhanded or wrong). Riyah could have talked through her issues with Devi, but didn't even consider it because she saw herself (and her son) as better than Devi. She only publicly raised her concerns when she wanted to get rid of Devi once and for all.

Devi _does_ have issues, but that doesn't mean she's undeserving of love, or that those issues compromise her ability to have relationships (friends, lovers, etc).