---
title: "Adventures in Consent"
date: 2023-04-06T11:32:42-04:00
draft: true
tags: ["diary"]
---
:toc:

== Chocolate

Last friday, I held a brown cookout for the brown people in my life. Someone who did not attend, we'll call them sapphire, gave me a ride to and from a grocery store. Along the way, the following exchange occured.

[quote, sapphire, chocolate]
----
So my high friends and I went to a strip club the summer after we graduated. As teen boys/young men do.

So we're there, and I notice one of friends is clearly very uncomfortable.

I pay this stripper, Chocolate, to give him a lap dance. You know, the experience.

He's obviously even more uncomfortable. Eventually even the stripper notices. She stops and says "Son, are you retarded?!"
----
+
_sapphire laughs_

I questioned sapphire, who proclaimed that they were the most self-aware toxic masculine man ever. I don't think saph realized the implicaition that he could not claim ignorance of the harm his actions caused.

Like many men, Saph is taught that sex is (at least partially) about power, status, and dominance. Saph wanted to exercise control over their friend, and used sex to do it. Saph's beliefs apply to both men and women despite (or perhaps because of) his heterosexuality. Thus being his friend (or a man) is not protection against sexual misconduct.

We also shouldn't dismiss the stripper's role in this. As a sex worker, she has a responsibility to ask consent from her clients, _especially_ when another has paid. 
I have difficulty classifying this incident as sexual assault/harassment/misconduct. This is because the one who violated boundaries and the one who wanted boundaries violated were not the same person. This is one of the problems about hearing this story years after the fact. Who knows that Saph's friend calls the experience themself.

I believe Saph does not entertain any genuine friendships. He is unable to tolerate the prescence of other men vying for his dominant position, to the point of misinterpreting other boisterous men's personality as a challenge.

I have (had?) a mutual friend with saph. I hope my friend see's this aspect to saph's personality, despite the benefits of saph's friendship.

== The Hypothetical Frat Party

I recounted the above anecdote to _another_ friend of a friend (I need to start being choosier with whom I socialize). This person, Jaabir, readily expressed that this was not assault.

[qanda]
Do you think this is sexual assault?::
No, of course not.

How so?::
Don't strippers avoid touching during a lap dance?

Well, he did not give consent::
He was in a strip club. He gave consent that way.

It was clear from his body language, both to the stripper and Sapphire, that he did not want this::
Yes, and its good that the stripper stopped. However, he did not verbally say "stop/no"

So if he had verbalized a lack of consent, then it would have been assault?::
No means No. But it would've only been misconduct if she continued after.

Lets look at this through the metaphor of a frat party.::
Sure.

A bunch of women (sorority sisters?) go to a frat party. Whilst there, one of them is groped or penetrated without consent. Is this assault/rape?::
Yes, of course. They didn't consent to any of that.

But they knew what they're getting into?::
I don't understand, please explain.

The sororities collect histories/accusations of sexual misconduct. They maintain these for both the fraternities and individual frat members. They use this as part of a vetting process when deciding which social events to attend and whom to engage in sexual/romantic relationships with. I can reasonably say these women knew what to expect when attending the frat party.::
While that's true, that's no excuse for getting groped.

Imagine instead a frat boy began dancing/grinding up against one of the girls. Would that be harassment?::
It depends.

Say it was clear from her body language she didn't want the grinding::
Well she should still say no. If he continues after that, thats harrassment.

What about the grinding from before she said no?::
No, thats just him determining if "shes down".

And if she had not said no?::
Then he's probably just having a good time. Its not like he's touching her. Could go wrong though.

What if he's groped her?::
That crosses the line. 

Going back to the strip club, what if the stripper brushed up against him?::
Its not the same. He's a guy.

Back to the party. Imagine the genders were reversed. What some girl had restrained or subdued a man and had sex with him?::
Where are you going with this? Its not like that even happens. Like c'mon.

