---
title: "America the Beautiful"
publishDate: 2023-12-25T12:27:16-05:00
date: 2023-09-30
draft: true
---

== Background

This summer, I started a new position at Capital One, an American bank.
I did not search for an apartment till the last minute, so I couldn't find a least in time for the first two months.
For the first month, I rented an airbnb with an old couple.
This covered the onboarding activities for new hires, but wasn't enough time to meet my team.
Within this second month, my team planned an outing for everyone who was "in the area" (some of us are wholly remote).

I decided to make it a vacation of sorts. I'd also visit my university on the way back.
While I went to work, I'd stay with family friends and commute.
The logistics were a bit hair raising (public transport go brr), so here it goes.

== Heading In

I took the Amtrak from my local station to DC.
Then the DC metro to my family friend's place. They live right next to a metro stop.
The door to door journey took much longer (about an hour) than expected.
I stopped at union station for dinner, and missed a metro train.

== Work

My hosts were very hospitable.
Their home cooked food was excellent, and it was fun hanging out with their son (who is my age).

I really enjoyed commuting by metro to work. I didn't have any transfers, and it was a short ride without many stops along my commute's stretch. Very peaceful.

I wished (and wish) that my the apartment I found was closer to or in DC. It would have made my commute shorter and I'd have been in a cooler area (not to mention closer to my university and the train station).

== Visiting My College

I took the metro from my hosts to my friend's house by campus. The journey would've been much shorter if I'd driven by car, but the metro was cheap on weekends and I was able to work while traveling.

I slept on someone's spare mattress, and visited many of my friends. I graduated in 3 years, so most of my college friends were still attending.
I think I must have tried to visit / catch up with over a dozen people in 36 hours, including but not limited to my ex and 2 friend groups.

== Heading Out

My university has cut bus services on weekends due to "staffing shortages" (pay a living wage please). There was also reduced bus service from the DC/MD transit authority.
I was left without a bus from campus to the nearest train station on the weekend, a glaring omission in coverage. I had a minor panic whilst I searched nearby bus routes.

I walked 25 mins to the next town, and caught a bus from there. It was an incredibly scenic route, through a park, beautiful and calm residential streets, and over a pedestrian footbridge over the metro rail. The bridge was very surprising, it windingly ascended some 4-5 levels to achieve the necessary height to clear the metro railcars. Both cyclists and pedestrians used it, which made me miss my bike.

The bus was 10 minutes late, so I needn't have rushed to the bus. It took a circuitous route. I noticed a greater proportion of elderly people aboard than usual, made me wonder what their lives were like since clearly none of them drove. They had their funny arguments and discussions about the weather and bus service interruptions.

I got aboard the train and was finally able to relax for a a few hours. I paid more attention to the passing scenery than usual, and was struck how beautiful everything looked than you're speeding past. Even dilapidated neighborhoods seemed to have a certain charm.

At my stop, the conductor / ticket collector / train everywoman opened the door, stuck her head out, and radioed to the driver how much distance he had to stop / align with the station.
I thought that was very metal.
She also found someone's AirPods and held onto them until the owner realized.

== Conclusion

I visited my friends at university, family friends, and work almost entirely using public transport. I felt proud to be an American, something I rarely feel.
I know other countries have public transport that puts us to shame, but just this once I felt a win.