---
title: "Fuck Stem"
date: 2023-03-02
description: \"Auditing\" non cs classes
---

This semester, I occasionally decided to instead go to classes that seemed interesting.

They actually _were_ super interesting and it made me rethink me life. CS is cool and all, its a mind puzzle and I like working out the brain muscles, and money is great. But this stuff is actually interesting to learn.

== FMSC330: Family Stuff

My friend took this class the previous semester, and sent me the slides for the entire semester. I thought it was great, so I sat in a few times this semester.

* Divorce, marriage, child rearing
* incarceration
* differing views on family structures
* sexuality, dating
* and much else!

== FMSC190: Men

Every feminist and men's rights activist should take this class. I feel like gender discourse is slanted in favor of women's experiences. Of course, there's nothing wrong with those stories, but it makes it seem like understanding (western conceptions of) gender is only for women.

There were frank discussions of the issues men face, the way they're socialized, and the way men perform their masculinity.

We talked about mental illness, violence, crime, depression, trauma, etc, misogyny, right wing politics, radicalization. We watch a short film (imo, was cringe) about a man struggling to remain nonviolent and a be a good father and husband. His probation officer warns him that good intentions are not enough. As a child, he was diagnosed with various things, adhd, biopolar, behavioral issues, etc. The closing scene is the man seeing a therapist who believes these diagnoses are all wrong, and he is likely suffering from some kind of trauma (PTSD, idrc what therapist said).

== RELS271: Religion

Genuine discussion of world religions and the philosophy behind them. I heard sat in on "Islam" and "Buddhism" days (but of which were part of longer units). So cool to hear students make comparisons and share their experiences. Unfortunately, basically all religious students were jewish and christian (I don't think irreligious students felt ok speaking). Way deeper and comprehensive than my "world history" education in 8th/9th.

I was able to connect some of what I heard with the way my friends acted.

== ANTH403: Queer Anthropology

Regret coming into this class only once! Very small, ~15 students? Very intimate, everyone did the reading and participated in class. Prof knew everyone's names and was an immaculately dressed gay man (slay).

The day I visited, talked about how technology affects our sense of self, and how that affects gender. I talked about Spacers from Foundation: how they were a first wave of immigration from earth and technologically superior, and none of that mattered once "teleportation" was invented and they were enslaved as the operators due to their physiology.