---
title: "India Driving"
date: 2023-07-21T04:28:12-04:00
tags: ['india']
---

A lot of the content online about driving in India is not from Brown people, and comes across as holier than thou. I think India is solidly middle of the pack when it comes to road safety ... whatever that means.

== Behavior

In India, people:

* Drive on the wrong side of the road
** While it happens all the time and you need to be prepared, its not like an onslaught. Smaller vehicles are more likely to do this

* disregard lanes as nonexistent / meaningless
** constantly switching lanes in an attempt to selfishly overtake people
** Straddling lanes out of indifference or trying to play both sides for overtaking

* Honk as a proximity alert, not a "get out of the way"
** Yes, this is noise pollution.
** No, its not out of rudeness.
** Yes, there are some especially bad drivers who will honk with abandon
** Yes, this leads to alarm fatigue.

* Try to fill every available space
** If your trying to turn, people will swarm you
** If there's a necessary slowdown, people will swarm you and prevent you from resuming normal speed

* Don't use turn signals

Mny of these issues would be mitigated if vehicle size was constant. Say, everyone drove autos.

== The roads

As for infrastructure:

* Bad roads
* Poorly visible stoplights with bad timings
* Bad intersections
* No exit lanes (or similar)

Road design is so much better in the US (we don't have roundabouts tho).

== Conclusion

I understand these issues are ultimately due to money. The government does not sufficiently invest in roads. Lots of people drive without license. Public transport is bad so driving is often necessary. Good road behavior is so infrequent that behaving can be disadvantageous, slow, unsafe.

Ultimately, it means the flow of traffic is much slower. For long journeys in the US, I can go twice as fast.

Holy crap, the public transportation in Zürich was godly. I cried.