---
title: "Exploring"
date: 2023-05-24T09:09:15-04:00
tags: ["diary"]
---

== Poem

I love snooping.
I love rifling through every draw.
I love flicking every switch.
I love turning every corner.
I love opening every box.
I love emptying every shelf.
I love perusing every tabletop.

== Joy

I've been like this since I was a child. I've consciously acknowledged it before, and even said it out loud. But this is the first time I've said it/thought it as an adult? The older I get the weirder it feels that I snoop. As a child, I didn't need to ask permission to wander about. As an adult, it seems strange to meet someone new, and then go through their house.

Novelty is definitely a part of this. I'm building a map of everything in the house. And once its built, I don't get as much fun out of exploring. Whenever I'd get the opportunity (as a child) to visit multiple times, it'd be a chance to update the map, or add unexplored sections of the house.

== Yesterday

Yesterday I arrived at my friend Russel's house. His family has so much stuff. I think there isn't a bare surface anywhere. Their pantry is packed. Tall stacks hiding yet more stacks.

And of course, he's chinese so .. stereotypes: Lots of food everywhere, multiple fridges.

I told him whilst going through his pantry, "I haven't had this much fun in years". I think I really meant this. He'd asked me beforehand "Do you do this to every house you go to?". I said yes, but the real answer was "I'd like to".


