---
title: "Where Do You Call Home"
date: 2023-12-17T19:05:20-05:00
---

> This is a response to Jason Kottke's post, since I am not a Kottke.org member.
> https://kottke.org/23/12/where-do-you-call-home

== Childhood

I grew up in a Central Jersey Suburb. The area is, and remains, unparalleled in its diversity outside of a major city. My town was nearly evenly split between whites, blacks, asians, and latinos. Many of the neighboring towns were homogenous. At least we all remained in close proximity to each other.

While I do think there was segregation of various forms (race, income, when your family immigrated, etc), it never felt mandatory. It was very easy to break out of your bubble.

When I talk to suburban Asians from other parts of the country, I'm struck by how they were either very clearly minorities (nearest asian store or temple far away, not too many asians on school), or they came from an extremely asian place.

My place in Jersey felt ... pluralistic? Is that te right word?

== College

I went to college and got my first job after college in the DMV area.
I'm overjoyed to spend time here with my college friends, most of whom are from the area.
But do I feel at home here?
No.

My college town is rapidly developing (attracting whom in the process, I don't know), pushing out lower income people (many of whom work at the university). There is a lack of affordable housing (both student housing and single family housing). College students (armed with parents' money) rent out many of the homes, 5 to a house.
Lower income people are being pushed out.

While I loved campus, it has been under massive construction for many years now.
Every few years a new development sprouts.
I'm sure in 10 years it'll be unrecognizable.

College Park never felt like home, it never felt like a town.
Some parts of campus are circumscribed by major roads, rivers, housing developments.
This means when students want to shop, hangout, etc, they have to exit from a single side of campus with only a handful of exits.
And they exit / enter from a main throughfare, which makes walking along it and crossing miserable.
Much of the activity is concentrated along this stretch of road, despite its inhospitality.
Whenever I returned back to my apartment or dorm after a night of partying, studying, hanging out, it never felt like I was going home.
The places I spent more often, like my friends rooms (which were larger), or the common areas we frequented felt like home.

Those common areas are also being transformed.
Campus leadership fails to acknowledge students need places to hang out, in various forms.
Places where individuals, small groups (3-6), and medium groups (7-20) people can comfortably hang out. Whether thats studying, gaming, just hanging out, whatever.

Common areas are being removed, reappropriated, or replaced with glamour or research space (never mind that the grad students also don't feel welcome).

== Young Adulthood

My first job out of college is also in the DMV area, but the specific spot I'm in doesn't feel organic. Its manufactured, not homily. Though there are nicer proper suburbs very close by.

The urban design is terrible here for all the same reasons urbanists talk about. The nearby pretty suburbs are also terrible for all the same reasons urbanists talk about.

== Where Do I feel home

The home I grew up in is where I feel at home. But only when my parents aren't in it.
Such a large space just for me (and/or my sibling) feels so wasteful (I could delete my parents' portions of the house and not notice).

My brother is a big part of the home feel for me.
Even if we're not talking much, his presence is grounding.

== Conclusion

My apartment near work needs _a lot_ of work/decor before it starts to feels like home. That's gonna be part of my New Year's Resolution.