---
title: "Poll Working"
description: Up close and ugly with American democracy 
date: 2023-06-06
---

Today I was a poll worker in New Jersey's Primary election. I was the only brown person, and one of 2 people below the age of 55. The other person was middle aged. Suffice it to say, almost everyone involved in the process was basically a retiree. It was a massive culture shock for me. I felt tapped into the soul of my country for a day.

== Democracy is Dead

I had to show up at 6am, which felt offensive. I know it's because the election was on a weekday, so theoretically people might come in before work. I was instantly out of place. We set up tablets to register people are having voted (they also let us look up voter registrations for those who didn't have their info on them). We averaged 1-3 people per hour voting. It was midday before I realized mail in voting exists. The majority of those who'd voted did so by mail (thanks jersey, thanks tablets). The actual voting was *not* the focus of the day for me, though we did jokingly compete on which table had the most voters.

== Long Live Democracy

By god the discussions we had! There was a general distrust of institutions (govt, large corporations, etc). There was one woman who repeated phrases like "my momma taught me to always look at the foundation of a thing" (evil institutions don't really change) and "the eagle is sick" (in reference to American life). 

They all spoke about how too many of their loved ones were getting afflicted with cancer. And I'm like .. have y'all seen how old you are??? Nutritious food (and in particular, produce) was so hard to access. Once again, I'm like ... yeah the big companies can make more money selling us unhealthy garbage because it's cheaper to make/ship. Our political system doesn't listen to the people. Yes, there's money in politics, low voter turnout, gerrymandering, disenfranchisement, and a dozen other issues. The doctors aren't listening to them, rob us blind, and are prescribing god knows what. Surprise surprise the insurance companies wants your money. Alternative medicine also came up. No way in hell was I gonna explain placebo. Thankfully, we kind of let this one go (agreed to disagree almost immediately).

Conspiratorial thinking was abound. It sucks how they all identified valid problems ... and then missed the mark on them. On all these issues, there was a lot of references to "them". "They" who control everything and want to ruin our lives. I struggled to communicate that in each of these situations, there was no evil hidden cabal of people pulling the strings. Just regular old greed, well understood problems, and equally well understood solutions.

Its worth mentioning that the space was multiracial: I'm brown, ofc there were plenty white people, 2-3 people were black, 1-2 people were latino. It was also mixed gender.

== Democracy is sick

Someone mentioned that all the older volunteers had died off, leaving it to the "next generation" (of people 55-70) to take over. Holy crap whatever democracy is left will be gone in my lifetime.

These folks were all *extremely* intelligent and verbal. We were gushing, a little too much. I'm starting to get tired of these me-vs-everyone discussions (previous topics include evolution, specific aspects of women's rights, queer representation and liberation). I'll let it slide this time out of respect for these folks. Even though there was very little convincing going on, I was getting more respected as the day went on. Not being dismissed, not talked over, listened to, responded to.

We could have gone so far with some science knowledge and political literacy. I get the sense that they might not get the chance to talk about these deeply held and important beliefs, least of all with someone so young and someone who disagrees respectfully. The quality of discourse was comparable to some discussions I've had in college. How did we as a society have missed the chance to educate this politically influential group?

By the end of the day, I thought everyone was crazy, and I think they knew that. I fucking loved it, being the star of the show. They were all offering me rides back home. I should have taken one of them up on the offer, but my dad came to get me.