---
title: "Loser"
date: 2023-09-31
publishDate: 2024-02-03T10:46:01-05:00
# Publish date is when written
tags: ["india"]
---

I met an uncle last summer when I visited India.
This uncle (along with several others) had stayed at my house for a few months/years when I was in elementary school.
My Parents let him the guest room whilst he pursued higher education in the US (he got his PhD, but the other uncles got masters or bachelors degrees iirc).
He tried to have a heart-to-heart with me, now that I was a grown man (I'd just graduated college, had a job lined up).

He'd invested quite a bit into the idea of coming to America.
He pursued higher education (and lived humbly during that time), he formed a support network out of my family, his extended family, and those he met during his studies.
In spite of all this, he still decided to settle back in India. Why?

== Staying In India

His PhD (in a computer engineering discipline I think) did not have a good rate of return on job prospects.
He found good job offers, both here and in India that would use his expertise, but nothing with a dramatic increase in pay / responsibilities from someone who'd accumulated the necessary experience from the industry.

So then he turned to cost of living. While an Indian salary is a lot less, he'd be upper middle class (which is saying a lot in a country that is still building its middle class, unlike in the US which had a large middle class and is now destroying it).
In India he owns a richly decorated home (it is narrow but with 5 floors, I love it), has a chauffeur, lives in a nice quiet area in/next to a bustling city (we'd call this a suburb in the US but that idea hasn't quite caught on there), and is preparing to sublet the basement. The neighborhood he lives in has a subterranean road leading to underground parking places for each home (their are stairs up to the house). This leaves the above ground road free for pedestrians.

He also lives with his mother, who provides free childcare and domestic labor, and has a maid who cooks and cleans. His sister is his neighbor and visits.

Its not perfect. I don't like having maid/servants/chauffeurs, servitude feels wrong (there's casteism to it in India).
His mom is clearly out of options (housework isn't intellectually stimulating).
His wife does a decent amount of housework (especially childcare) despite also working.
The housing development feels very artificial (the ground outside is a waterproof cheap plastic tile), despite the homes' beauty.

== Regrets are for Losers

He took me out to get a suit tailored. A lavish gift. I need to lose weight to look good in it.

We were talking about missteps we'd made / might make in our careers and academic prospects. He told me to not talk to much about these mistakes though, and certainly never complain.
If you complain it means your not enjoying your current life, or are bogged down by regrets. And if you do, you're a "Loser".

This was harsh, but looking back on this after half a year, I appreciate the reminder.

There are lots of things right now that I want to improve about my life (right now I'm thinking of moving).
But in 10 years will I really remember these issues? Most likely I will find other things to worry about.
Will fixing these issues really make me happier or make meaningful difference in my life (health, family, career)?
Lots of my issues are temporary slumps that won't affect me down the line.