---
title: "On Writing"
date: "2024-02-13T22:14:52-05:00"
description: "How and Why I write"
---

For most of my life I hated writing.
I didn't like the stilted questions we'd consider in english class.
My writing skills were poor (and I was repeatedly told this).
I was put in https://www.linkedin.com/in/lestergesteland[english tutoring] (with well meaning and skilled instructors) and still didn't get it.

== The Past

In high school, I tried to type as much as possible (aided by my personal laptop, an incredible privilege).
I did not take notes in science and math classes, since I found everything easy.
I did not take notes in english classes, because I found content to be disorganized or not worth writing (this is my opinion, not a fact. I'm still learning to appreciate literature).
I even learnt some basic latex syntax to type math, though I did not submit full latex documents (I didn't have the patience/experience to learn/know anything more complicated than markdown).
Typing was the language of information and ideas, writing was the act of degrading yourself and slowing down.
And yet, what a hassle it was to type math in latex in google docs, slowly convert them to images, and print everything (math hw was submitted physically pre-covid).
My printed sheets stood out in submission piles and made me a target for teachers (not out of malice. I made careless arithmetic errors and typed assignments made them trivial to find).
Alas, I HATED writing in notebooks and wide tipped pens. Wide ruled and 0.7mm were terrible, college ruled and 0.5mm were barely tolerable.

I starting link:{{< ref "/posts/2023-02-18-Blog-History">}}[adding to this blog] around the time I started college.
I was copying other tech bloggers.
They wrote about interesting technical content and I wanted to emulate them.

== The Present

However, almost immediately my blog turned into my public diary.
For the first time in my life I had a place of my own to write.
Not school assignments, and not personal notebooks my parents might monitor.
(I had a strange habit of accumulating stationery I wouldn't use as a child. Probably my desire to write peeking through. Or maybe I found stationery cool).
It was a lot easier to write what was swirling around in my head, my life, even though the quality wasn't (and isn't) great.

Very little of the content here is technical, so I created the "dev" and "diary" tags.

In parallel to my blog, I gained experience with note-taking discipline in college.
For the first time, I couldn't keep everything in my head in math/computer classes (though concepts were still usually easy).
The math lecture style (and to a much lesser extent, cs lecture style) was very easy for note taking.
You mostly copy whats on the board: definitions, theorems, example problems, diagrams and figures.
You are free to omit stuff, add detail, draw connections, etc.
It was a lot easier to write out math, especially since I began *collaborating* with classmates on paper and the board.
Writing helped me not just remember, but to collect my thoughts, organize them, and make them flow.
Typing math was solely for submission and presentation / prettifying afterwards (as all my peers already knew).

Sophomore year of college, my SDU program took a trip to NYC. A Chinese friend took us to a Japanese store, Muji.
There I found notebooks with narrow lines (even narrower than college ruled) and 0.38mm pens.
I filled a large notebook with math, purchased a second smaller notebook a few months/a year later on another NYC trip, then  when I couldn't find anything else with narrow lines. I emptied 2-3 muji pens in the process, about 1 per semester.
I scrounged high and low for some random pocketbooks and the narrowest pens when these all ran out, throwing out 7-8 gifted notebooks rather than return to normal American office supplies.
I went from 0 to 100 in collage and it felt so natural (if exhausting, since it was all schoolwork).
My handwriting had always been small and cramped, and finally this was no longer a limitation.
College gave me a reason and space to write, and Muji gave me the ability to write.

== The Future

https://gilest.org/indie-easy.html[Publishing here] has a lot of https://gilest.org/indie-easy-again.html[friction].
I have to

. Create the post text file. It must be correctly formatted ( there is a metadata header) and named.
. Commit and push. Git history is complete overkill. The vast majority of posts have an initial commit with all content, then some follow up commits with typo and formatting fixes. VCS is not useful for my content. It _is_ useful for the non-content (CI config, hugo config, website environment).
. Have CI rebuild and publish my site. There's no "build cache", so the entire site is rebuilt and copied to github pages. Ideally, only changed files would be rebuilt / copied. Alas, this is not hugo's way (and it only matters because I chose adoc over md).

Typing doesn't help my thoughts flow as much as handwriting (but is better at crystallizing them). So the barrier to spontaneity and creativity is artificially high.
Perhaps I should https://posthaven.com/[consider] https://www.realmacsoftware.com/rapidweaver/[a] https://pika.page/[blogging] https://bearblog.dev/discover/[platform] https://substack.com/[instead] of an SSG/CI.

Still I wasn't fully satisfied with this status quo upon graduating college. My blog contained diary entries (some unpublished due to privacy and embarrassment) and technical content (far and few in between), and my notebooks contained schoolwork and ideas.
This was an uncomfortable division.
I'd learnt latex and asciidoc while in college, which helped bring my schoolwork and ideas into digital format.
But the reverse direction, bringing my diary entries and technical content to paper hadn't happened.
I resolved to fix this.

I returned to NYC (and Muji) for a ¡third! time in Nov 2023 with college friends and bought another notebook and pens.
Once again my output boomed, but this time I poured my emotions out rather than crack problems.
I didn't have to worry about others seeing what I write.
Fuck quality, or meaning, or respectability.
I've written the deranged, the mundane, and everything in between.

It removed tremendous pressure from my blog's diary entries to be perfect or well-formed. I have half a mind to delete many of these old entries, but I won't 😉.
