---
title: "I will never own a home"
date: 2024-03-14T23:28:44-04:00
---

This is a weird blog post.
An (fairly onsided) argument occurred in my company's slack about the housing market, about whether it was ethical to rent out a home (especially in today's market).
It got me thinking.
The employees having this argument were some of the highest income earners in the country.
Surely *I* would be able to own a home right?
Right?

I started from the generous assumption that I'd be married, bringing my family income to $200k.
I'm not so delusional to assume I could own a home singlehandedly.
This isn't 1965 lol.
This income is already much higher than the median American family.
Marriage is generous assumption because marriage is dead in my age cohort. Marriage has also been uncommon amongst queer people in the US (yay homophobia).
Marriage is off the cards for me, but we'll assume it is.

If we use nerdwallet's buy vs rent calculator to see what my family could afford, and plug that into Zillow's real estate listings ...
We can _just barely_ afford a slightly smaller home in a slightly worse neighborhood than what/where I grew up.
I have no problems downsizing (my home was massive, we did not use the space efficiently).

In this scenario, I would be childless.
Which doesn't bother me, if my friends and colleagues also remained childless.
But that part is unlikely (they make similar money and are straight, and so are likely to get married and have kids).

Downsizing also doesn't bother me.
However, I cannot stomach sacrificing neighborhood quality (in terms of urban design: accessibility, green space, local businesses, etc).

The primary purpose of home ownership is to build _some_ marginal wealth and security (not to be rich, but to have _some_ stability even in hard times).
But if I don't have a spouse or kids, there's no motivation for me to own a home.

== Lessons learnt

Assuming no parental help, home ownership is out of reach for the upper middle class as well.
I thought at least for someone of my income, marriage would make ownership work. But no, the problem is too bad for even dual income to help.

I was also surprised by how close the costs of buying vs renting were over a 30 year period (in many cases).
If things were just a bit better, things would be a lot better for many (but not most) people.

I also learnt about the time scale at which such things operate, looking ahead 10-30 years is enough to give a good understand of one's situation.
It also shows why problems (and solutions) with our economy can take so long to show up for the majority of people.
