---
title: "Roomates"
date: 2024-09-29T21:43:21-04:00
description: A curious encounter with a potential tenant
---
:fn-shilling: footnote:shill[I guess _I'm_ the one selling the apartment now, despite leaving]

So I'm moving!
I don't like my current town, and I don't like my current roommate (nothing serious, we just don't jell well).
Housing is unaffordable pretty much everywhere, and its resulted in some interesting characters coming by trying to replace me as a roommate.

Today's prospective tenant came by motorcycle.
He strode into our apartment with a very styling motorcycling outfit (it was black, windproof, made him look beefy).
I thought he was cute.

My current roommate is an immigrant, and I can tell he's unfamiliar with our guest's American mannerisms.
I decide to intervene in the conversation.{fn-shilling}

== I flex my American'ing skills

[quanda]
So where do you work?::
Oh, in a "far out suburb of DC"

Why are you looking at our apartment unit then? We're closer to DC, and rent is higher here. You;d be much happier closer to work::
Oh rent seemed really high everywhere, so I'm just looking anywhere I can get.

Oof yeah, but that doesn't quite answer my question?::
He mentions offhand something needing a place for his young children when they're occasionally.

_My roommate is visibly shocked._

I put two and two together. Young man with kids part time. LMFAO. Sounds like a standard military divorce.

Is that your custody arrangement?::
Yup

How long were you two together?::
5 years

5 years is a long time at our age::
It sure felt like it, I'm 26

Now my brain is extra big, stereotypes coursing through my veins. He's rural based on his accent, and a young divorcée

Did you serve?::
Yup, got out a few years ago.

I can explain the local housing market, if you'd like? New construction often has discounts for their first tenants, and AirBnB owners will give you better rents if you pay cash.::
Look at this man playing the system here. Fucking crazy man. I'm from an area where housing is still affordable.

Well (immigrant) community is important to me. I'm sure I could buy 10 houses in Nebraska, but I don't care about bumfuck nowhere.::

Sounds self inflicted.

A little bit man, a little bit. I also don't wanna be the only brown person somewhere you clueless cunt.

Oh you know, there's a lot of brown families who rent out their finished basements to young families. Its a great way to get started here. The price is usually set for two working adults, but you might make it work::
Man the racism up here is crazy. People always say the south is worse but the things I've heard since I've gotten here..

I'm from the North East, things are certainly better there. Not sure what you meant by racist though, was simply stating a fact about the local immigrant population  (of which I am a part)

So you do realize this is an apartment? Not much room here for kids?::
Eh, I know how to make do. When I have them over I usually take them to my boat

I try to hide my disbelief, and do my best to remember that article about a guy who was raised out of a boat while living in the tropics.

Where's your boat? On the potomac?::
Oh man I wish.

Lmfao I just uttered the one body of water I know, hope I didn't come across as dumb.

== Debriefing

My roomate and I laughed at the encounter.
I felt bad my roommate was going to such lengths to replace me.
Also felt bad this man couldn't find a place for his kids.
I sent him a couple listings to be nice
