---
title: "Wheel of Time"
date: "2025-06-22T21:42:10-04:00"
---

So the https://en.wikipedia.org/wiki/The_Wheel_of_Time_(TV_series)[The Wheel of Time] was cancelled by Amazon.
I couldn't stop myself from watching it, despite not liking it.
It scratched an itch for fantasy content.

I thought it was very sexist and poorly written.
Shoouldn't have trusted the reviews on reddit before I watched it.
They said that women alone have magic, and this "greatly affects" the plot.
Of course I didn't believe that having women characters would mean much, but there was so much hype.

== Rand

Rand is sexist.
He is jealous of Egwene studying magic and becoming independent / leaving him.
But as far as we can tell, he has no reason for this.
It seems women are independent in-universe, regardless of profession.
And Aes Sedai seem allowed to have romantic partners?
Now the Womens' Circle (religious organization of magicians in their hometown) seems to prohibit relationships, but thats never deeply explored.
And both Egwene and Nynaeve seem to not care about this since they're main characters.
Yeah so Rand is an incel.

// TODO: Rand arrogance

== Mat

=== Dragon Reborn Reveal

Rand is told he's The Chosen One by a disembodied voice in a throwaway scene.
This comes after a season of ambiguity.
Of course, it was obviously always going to be him, the white man.

== Morraine

Morraine is never dirty looking, despite trekking across the world on foot.
She's also just a bad person?
Even without analyzing her actions, she always talks like her goals are more important or that she knows best.
She lies to the MCs, and asks Lanphear to attempt to assassinate them.
After all this, Rand somehow think she alone has his best interests at heart.
It felt so incongruous of him to think that, after his previous mistrust of her (and insecurity towards of Egwene)

== Liandrin

So Liandrin is a misandrist ..... because she was sexually abused as a child.
This is totally reasonable. But rather than trying to ... I don't know give her therapy, her misandry is used a signal of her evilness.
Her misandry is even more justified when you consider that male magicians are OFFICIALLY more powerful and also go mad.

She stills Logaine Ablar, and this is supposed to portrayed as an overreaction.
But Logaine was a warlord, well into his mental decline, and had just killed her colleague.
Logaine being stilled and imprisoned in an insane asylum is honestly a pretty good outcome.

She also hates Rand, who has fully committed to abusing his powers.

== Outfits

The women constantly get new and ostentatious outfits, even between scenes where costume changes make no sense.
After Liandran escapes from the white tower, she wear a red wedding dress.
It looks amazing ... and ridiculous.

Lanphear is the worst offender, even though her white and black color scheme is to die for.
She changes outfits between Rand dumping her and attacking Morraine.

=== Hair

Almost all the women are wearing wigs / extensions.
It gives the impression that its a necessary part of the dress code of being a (powerful) women.

=== Butch

While a minority of women (and side characters) do wear butch clothing (Lanphear, Min, the Blue sitter), they are not exempt from the elaborate outfits.
I don't get why powerful women would wear outfits designed to look good to men, especially when apparently androgynous or butch clothing is considered acceptable (if rare).

== Fights and powerscaling

Keep in mind that the most common usages of magic are healing, shitty telekinesis, and energy blasts.

== Gender-based power differential

So apparently men are more powerful than women? Just blatant sexism.
And leaves little room for creativity in battle (WHICH WE KNOW IS POSSIBLE).

Also more powerful people need less training? Ew.
Rand gets no on-screen magical training (vomiting doesn't count), and easily beats two Foresaken and controls the weather.
Nynaeve parts a river without trying (guess we should just almost killing the MCs so they get power boosts).
Egwene is the only one seen practicing and progressing.

== Lanphear

Lanphear is defeated by Morraine and her magic ball despite displaying significantly greater breadth and depth of power than anyone else.

Lanphear easily

* creates massive explosions
* decapitates people
* opens portals with a wrist flick (shown to be much harder for others)
* glues someone's lips together
* makes mirror-glass warriors (remotely)
* gives tattoos
* Telekinetically flings weapons around (remotely)
* Made pictures dance around,
* Dreamwalks (an allegedly rare skill)
* Is biologically immortal

== The Other Foresaken

Samael has a magic hammer. Ishamael frees the other Forsaken, learns to dreamwalk, can create bullets, and project illusions.

But none of this matter when Rand can one shot both of them.

=== Magic White Ball

Morraine just randomly finds a magic white ball that boosts her power?
No trials or anything?

== World Building

== Satan

The bad guy is called Saitan / The Dark One.
He never talks to anyone.
He was accidentally set free thousands of years ago by overly ambitious scientists.
His followers are called Dark Friends and recieve mysterious benefits for following him.
Its all so on the nose.

Morraine's nephew gains wealth and influence after becoming evil. How?

Lan meets a survivor woman from the same kingdom as him.
She promises Satan to kill Lan, and dies when she violates her oath.
Why was breaking your evil promises never explained sooner?
It would've explained why no one defects from Team Satan.
Except for Lanphear who tries to run away with Rand instead of killing him.
No instant death for her.

== The Desert Warriors / Aiel

Apparently they're all super violent as an overreaction to being an offshoot of a pacifist tribe.
Makes total sense.

Also the they just have some magic architecture that shows you the past / future.
No outsider has ever found this?
The Aiel themselves make no little to no use of these artifacts, despite it being a part of their culture and rites of passage.
Also these artifacts convenient give Rand tattoos marking him as the Chosen One.
Since apparently the Aiel are too stupid to notice when he easily defeats Samael.
Too convenient.

Also these magical artifacts show that Rand is every important historical figure ever.
How nice for him.
Although I thought Rand's past life as Lews Therin was a Black man, so clearly that's been retconned out.
